targets:
  $default:
    builders:
      stacked_generator|stackedRouterGenerator:
        options:
          navigator2: true
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
          - integration_test/**.dart