name: dionniebee
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.10
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  carousel_slider: ^4.2.1
  faker: ^2.1.0
  url_strategy: ^0.2.0
  badges: ^3.1.1
  another_transformer_page_view: ^2.0.1
  smooth_page_indicator: ^1.1.0

  collection: ^1.17.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.8.1
  stacked: ^3.4.1
  stacked_services: ^1.2.0
  stacked_themes: ^0.3.12
  reactive_forms: ^16.0.2
  reactive_date_time_picker: ^3.0.0
  reactive_forms_annotations: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0
  intl: ^0.18.0
  uuid: ^4.2.1
  responsive_builder: ^0.7.0
  flutter_animate: ^4.2.0+1
  cached_network_image: ^3.2.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  dartz: ^0.10.1
  scaled_app: ^2.0.0
  flutter_map: ^5.0.0
  flutter_map_dragmarker: ^5.0.0
  loader_overlay: ^4.0.0
  flutter_map_animations: ^0.4.1
  custom_map_markers: ^0.0.2+1
  flutter_map_marker_cluster: ^1.2.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocode: ^1.0.3
  rename: ^2.1.1
  flutter_cache_manager: ^3.3.1
  http: ^1.1.0
  animate_do: ^3.0.2
  coupon_uikit: ^0.2.0
  rxdart: ^0.27.7
  cloud_firestore: ^4.8.5
  fluttertoast: ^8.2.2
  app_settings: ^5.0.0
  permission_handler: ^11.1.0
  sliding_up_panel: ^2.0.0+1
  geoflutterfire2: ^2.3.15
  flutter_hooks: ^0.20.1
  money2: ^4.0.0
  shared_preferences: ^2.2.2

  
dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.1
  freezed: ^2.3.5
  stacked_generator: ^1.4.0
  hive_generator: ^2.0.0
  reactive_forms_generator: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  
  

flutter:
  assets:
    - assets/
    - assets/sliders/
    - assets/jollibot/
    - assets/carousel/
    - assets/icons/
    - google_fonts/
  uses-material-design: true

